languageCode = "en-us"
title = "Aftnet"
baseURL = "https://www.aftnet.net/"
canonifyURLs = true

[params]
  SiteName = "Aftnet"
  Author = "Aftnet"
  Email = "contact@aftnet.net"
  SiteDescription = "Aftnet Software Development"
  TagLine = "Quality apps, custom built"
  Thumbnail = "/assets/img/logo.png"
  Copyright = "© 2024 Aftnet"
  GoogleAnalyticsId = "UA-22182855-1"

[caches]
  [caches.images]
    dir = ':cacheDir/images'